"""Turns Derslok's note_table.bin into the C++ table the macOS map-note patch embeds.

    python macos/tools/make_map_notes_table.py NOTE_TABLE_BIN OUTPUT_INC

The input is 16-byte entries of four little-endian floats: shipped X, shipped Y,
corrected X, corrected Y. The patch matches the shipped pair bitwise, so the keys are
written as their bit patterns. Refuses a table whose keys repeat, or where a corrected
position is itself a key (the correction is applied in place and must not chain).
"""
import hashlib
import struct
import sys
from pathlib import Path

EXPECTED_SHA256 = "880a325d982d74df496b02782faefdd3ae3802efbba030b9fbccc967cc0ccaa5"


def bits(value: float) -> int:
    return struct.unpack("<I", struct.pack("<f", value))[0]


def main() -> int:
    source, output = Path(sys.argv[1]), Path(sys.argv[2])
    data = source.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED_SHA256:
        print(f"note table SHA-256 {digest} is not the K1 Area Map Fixes 1.0.0 table", file=sys.stderr)
        return 1
    if len(data) % 16:
        print("note table length is not a multiple of 16", file=sys.stderr)
        return 1
    rows = [struct.unpack_from("<IIff", data, offset) for offset in range(0, len(data), 16)]
    keys = {(kx, ky) for kx, ky, _, _ in rows}
    if len(keys) != len(rows):
        print("note table repeats a key", file=sys.stderr)
        return 1
    if keys & {(bits(x), bits(y)) for _, _, x, y in rows}:
        print("a corrected position is also a key; in-place correction would chain", file=sys.stderr)
        return 1
    lines = [
        f"// Generated by macos/tools/make_map_notes_table.py from note_table.bin",
        f"// (SHA-256 {digest}); {len(rows)} entries. Do not edit.",
        "const NoteCorrection kNotes[] = {",
    ]
    for kx, ky, x, y in rows:
        lines.append(f"    {{0x{kx:08x}u, 0x{ky:08x}u, {x!r}f, {y!r}f}},")
    lines.append("};")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{output}: {len(rows)} corrections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
