// KMRP for macOS: Derslok's area-map note corrections as a KotOR Patch Manager patch.
//
// BioWare shipped 250 map notes whose stored world position does not match their subject,
// so the area-map marker sits beside the door or terminal it names (a 2003 content bug,
// present at any resolution). KMRP corrects them on Windows from Derslok's hand-measured
// table (K1 Area Map Fixes 1.0.0, GPL-3.0, bundled with his permission); this is the same
// table, embedded at build time from
//   third_party/Included/K1-Area-Map-Fixes-1.0.0 by derslok/More info/source/data/note_table.bin
// 250 entries of four little-endian floats {shipped X, shipped Y, corrected X, corrected Y}.
//
// Hook: CSWGuiMapHider::Draw's note loop (KOTOR_Exe 1.4.0, C1FCB8D3...6D71). For each note it
// looks the note's object up, then at 0x1002b4f52 tests the object's map-note flag and reads
// its world position at +0xd8 (x, y) and +0xe0 (z) for the world->map conversion. The detour
// there (rbx = the note object) replaces x, y in place when the pair is a shipped key.
// Matching is bitwise, on the module's own stored floats, so it is exact; no corrected
// position is itself a key (checked when the table is generated), so a corrected note is
// never corrected twice. Draw also places the note controls that HitCheckMouse tests, so
// clicks follow the corrected markers.
#include <cstdint>
#include <cstring>

#include "../kmrp-layout/options.h"

namespace {
struct NoteCorrection {
    uint32_t keyX, keyY;  // shipped position, bit pattern
    float x, y;           // corrected position
};

#include "map_notes_table.inc"  // kNotes[], generated by build.sh

const uintptr_t kPositionOffset = 0xd8;
}  // namespace

extern "C" void KMRP_CorrectMapNotePosition(char* note) {
    // The hook stays whatever was chosen, as on Windows, where only the controller's depend on
    // an option; with map notes off the positions are left as BioWare shipped them.
    if (!note || !kmrp::MapNotesOption()) return;
    float* position = reinterpret_cast<float*>(note + kPositionOffset);
    uint32_t kx, ky;
    std::memcpy(&kx, &position[0], 4);
    std::memcpy(&ky, &position[1], 4);
    for (const NoteCorrection& entry : kNotes) {
        if (entry.keyX == kx && entry.keyY == ky) {
            position[0] = entry.x;
            position[1] = entry.y;
            return;
        }
    }
}
