#!/usr/bin/env python3
"""Report which Override files KMRP would take over from another mod.

KMRP claims two sets of Override paths, and only one of them is written down:

* the shipped archives -- the common textures and the per-resolution GUI layout;
* the ability icons, which do not exist until patch time. They are generated by
  upscaling entries out of the game's own ``TexturePacks/swpc_tex_gui.erf``, so
  the list depends on the installed game rather than on anything in this repo.

That second set is the interesting one for compatibility. The generator reads the
**vanilla** texture pack, not Override, so an icon another mod has fixed is
replaced by an upscaled vanilla version for as long as KMRP is installed. It is
reversible -- restore records every file it replaced and puts it back -- but while
patched the other mod's art is not what the game shows.

Usage, after installing the other mod on a clean copy::

    python tools/check_override_conflicts.py "C:\\Star Wars - KotOR"
    python tools/check_override_conflicts.py "C:\\clean\\Override" --game "C:\\clean"

Pass either the game folder or an Override folder directly. ``--game`` names the
install whose texture pack should be read, when that differs from the folder being
inspected.
"""

from __future__ import annotations

import argparse
import struct
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ARCHIVES = REPO / "build/universal-patcher/resources"

ERF_KEY_RECORD = 24
ERF_RESOURCE_RECORD = 8
RESOURCE_TYPE_TPC = 3007


def shipped_paths() -> dict[str, set[str]]:
    """Override names inside the built archives, as two groups.

    Only one resolution archive is ever installed, but every resolution ships the
    same file *names* -- the layouts differ, the names do not -- so for collision
    purposes their union is the same set as any one of them.
    """
    if not ARCHIVES.is_dir():
        sys.exit("No built resources at %s -- run build_universal_patcher.ps1 first." % ARCHIVES)
    groups: dict[str, set[str]] = {"common textures": set(), "resolution layout": set()}
    for archive in sorted(ARCHIVES.glob("*.zip")):
        with zipfile.ZipFile(archive) as bundle:
            names = {n.lower() for n in bundle.namelist() if not n.endswith("/")}
        key = "resolution layout" if archive.name.startswith("gui-") else "common textures"
        groups[key] |= names
    return {k: v for k, v in groups.items() if v}


def generated_icons(game_root: Path, reserved: set[str]) -> set[str]:
    """The ability icons KMRP would generate for this install.

    Mirrors AbilityIconGenerator: every TPC entry named i_* or ip_*, minus any
    name a shipped archive already claims -- `i_` is not exclusive to ability
    icons, and two archives writing one path is what broke restore once before.
    """
    pack = game_root / "TexturePacks" / "swpc_tex_gui.erf"
    if not pack.is_file():
        print("  (no %s -- icons would stay vanilla-sized)" % pack)
        return set()

    data = pack.read_bytes()
    if len(data) < 0x20 or data[:4] != b"ERF ":
        print("  (%s is not an ERF -- icons would stay vanilla-sized)" % pack)
        return set()

    count, = struct.unpack_from("<i", data, 16)
    keys_at, = struct.unpack_from("<i", data, 24)
    names: set[str] = set()
    for index in range(count):
        key_at = keys_at + index * ERF_KEY_RECORD
        if key_at + ERF_KEY_RECORD > len(data):
            break
        kind, = struct.unpack_from("<H", data, key_at + 20)
        if kind != RESOURCE_TYPE_TPC:
            continue
        raw = data[key_at:key_at + 16]
        name = raw.split(b"\0", 1)[0].decode("ascii", "replace").lower()
        if not (name.startswith("i_") or name.startswith("ip_")):
            continue
        candidate = name + ".tga"
        if candidate in reserved:
            continue
        names.add(candidate)
    return names


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("target", type=Path,
                        help="the other mod's game folder, or its Override folder")
    parser.add_argument("--game", type=Path, default=None,
                        help="game folder whose texture pack to read, if different")
    args = parser.parse_args()

    target = args.target.resolve()
    override = target if target.name.lower() == "override" else target / "Override"
    game_root = (args.game.resolve() if args.game
                 else (target.parent if target.name.lower() == "override" else target))

    if not override.is_dir():
        sys.exit("No Override folder at %s" % override)

    print("KMRP claimed paths")
    shipped = shipped_paths()
    reserved: set[str] = set()
    for name, paths in shipped.items():
        print("  %-26s %4d" % (name, len(paths)))
        reserved |= paths
    icons = generated_icons(game_root, reserved)
    print("  %-26s %4d  (generated at patch time)" % ("ability icons", len(icons)))
    claimed = reserved | icons
    print("  %-26s %4d" % ("total", len(claimed)))

    present = {p.name.lower(): p for p in override.iterdir() if p.is_file()}
    print("\n%s\n  %d files" % (override, len(present)))

    # Same name, same extension: KMRP overwrites it outright.
    direct = sorted(name for name in present if name in claimed)
    # Same resref, different extension. Both files end up in Override and the
    # engine picks one; which it prefers is not verified here.
    claimed_stems = {name.rsplit(".", 1)[0] for name in claimed}
    stem_only = sorted(name for name in present
                       if name not in claimed
                       and name.rsplit(".", 1)[0] in claimed_stems)

    print("\nDirect collisions (KMRP replaces these): %d" % len(direct))
    for name in direct:
        origin = "generated icon" if name in icons else "shipped"
        print("   %-28s  %s" % (name, origin))

    print("\nSame resref, different extension: %d" % len(stem_only))
    print("  Both files land in Override; which one the engine uses is not")
    print("  established here. Worth a playtest if any are listed.")
    for name in stem_only:
        print("   %s" % name)

    if not direct and not stem_only:
        print("\nNo overlap. The two mods touch disjoint Override paths.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
