#!/usr/bin/env python3
"""What every controller input actually does, screen by screen.

This resolves each panel's event handler to the engine functions it calls, so a
row says what a button *does* rather than which event id it delivers. An event
arriving proves the wiring; it does not prove the screen responds, and those are
different claims.

Three sources are joined:

  reverse-engineering/retained-gui-event-inventory.txt
        every panel, its dispatcher, and the handler address for each event it
        implements. Regenerated by tools/map_retained_gui_events.py.

  the executable
        each handler is disassembled to the first return and its call targets
        collected, which is what turns "event 0x35 is implemented" into
        "calls CGuiInGame::PrevSWInGameGui".

  build/research/.../kotor1_0_3.db
        function names for those call targets.

The KMRP side -- which physical button sends which event, and which screens the
spatial navigation layer drives -- is declared below and must match
src/controller-native/K1NativeJoystick.cpp. The test suite checks the bindings
live; this file is the reference for what they mean.

Nothing here touches the game. It is a static pass whose output is then checked
against the running game by testing/controller/audit_screen_behaviour.py.

Documentation standard: see `docs/documentation-standard.md`.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "reverse-engineering" / "retained-gui-event-inventory.txt"
SYMBOLS = (ROOT / "build" / "research" / "Kotor-Patch-Manager" /
           "AddressDatabases" / "kotor1_0_3.db")
EXE_CANDIDATES = [
    Path(r"C:\Star Wars - KotOR\swkotor.exe"),
    Path(r"E:\SteamLibrary\steamapps\common\swkotor\swkotor.exe"),
]

# ---------------------------------------------------------------- the mapping
#
# Physical button -> the event KMRP's native path emits, its control slot, and
# the DIJOYSTATE offset the +0x164 table resolves that slot to. Mirrors
# K1NativeJoystick.cpp; testing/controller/test_native_input.py proves it live.

BUTTON_EVENTS = {
    "A":     (0x27, 0x74, 0x30, "KMRP native joystick event"),
    "B":     (0x28, 0x75, 0x31, "KMRP native joystick event"),
    "X":     (0x29, 0x76, 0x32, "KMRP native joystick event"),
    "Y":     (0x2A, 0x77, 0x33, "KMRP native joystick event"),
    "LB":    (0x39, 0x78, 0x34, "KMRP native joystick event"),
    "RB":    (0x3A, 0x79, 0x35, "KMRP native joystick event"),
    "Back":  (0x2B, 0x7A, 0x36, "KMRP native joystick event"),
    "LT":    (0x35, 0x7B, 0x37, "KMRP native joystick event"),
    "RT":    (0x36, 0x7D, 0x39, "KMRP native joystick event"),
    "Start": (0x0B, 0x7C, 0x38, "Native KOTOR retained event"),
    "Up":    (0x31, 0x7F, 0x384, "KMRP native joystick event"),
    "Down":  (0x32, 0x81, 0x388, "KMRP native joystick event"),
    "Left":  (0x2F, 0x80, 0x38C, "KMRP native joystick event"),
    "Right": (0x30, 0x82, 0x390, "KMRP native joystick event"),
    "R3":    (0x01, 0x7E, 0x3A, "Native KOTOR retained event"),
}

# Aliases some dispatchers list ALONGSIDE the primary code, reaching the same
# handler. They are recorded for completeness and are deliberately NOT used to
# resolve a button: sending 0x27 does not reach a handler registered only for
# 0x2D, because the dispatcher switches on the code it was given. The Main Menu
# is the case that matters -- it implements 0x2D and not 0x27, and A works there
# through the focused control, not through the panel.
EVENT_ALIASES = {
    0x27: [0x2D],          # confirm
    0x28: [0x2E],          # cancel
    0x31: [0x3D],          # scroll up
    0x32: [0x3E],          # scroll down
    0x2F: [0x3F],          # left
    0x30: [0x40],          # right
}

DIRECTION_EVENTS = {0x2F, 0x30, 0x31, 0x32, 0x3D, 0x3E, 0x3F, 0x40}

# Buttons handled by CClientExoAppInternal::HandleInputEvent, the action router,
# rather than by whichever panel is in front. They behave the same on every
# screen, which is exactly why they are not looked up per panel.
ROUTER_BUTTONS = {
    "Start": ("action router 0x006213BC: shows the in-game GUI when the module "
              "state reads 3, hides it otherwise -- so it opens the menu from "
              "gameplay and does nothing once a screen is up",
              "Native KOTOR retained event (action router)"),
    "R3":    ("action router 0x006216C7: CSWCModule::SetFreeLookCamera and input "
              "class 4 to enter; 0x0062184C: RestoreCamera and SetInputClass(0) "
              "to leave. Gated on a live player and not paused by combat",
              "Native KOTOR retained event (action router)"),
}

# Panels whose own dispatcher implements the directions: KMRP's navigation layer
# declines on these. Derived below from the inventory, not typed in.

# Control classes that consume the directions themselves.
LIST_CONTROL_DISPATCHERS = {
    0x0041A9D0: "CSWGuiNavigable / CSWGuiEditbox",
    0x0041CE20: "CSWGuiListBox",
    0x0041ADF0: "CSWGuiSlider",
}

# Calls that say nothing about behaviour.
NOISE = {
    "Global::return_zero", "Global::self_return", "CExoString::Constructor",
    "CExoString::Destructor", "CExoString::operator=",
}


def load_symbols() -> dict:
    if not SYMBOLS.exists():
        return {}
    connection = sqlite3.connect(SYMBOLS)
    out = {}
    for address, klass, function in connection.execute(
            "select address, class_name, function_name from functions"):
        out[address] = f"{klass}::{function}" if klass else function
    return out


class Image:
    """Just enough PE to disassemble at a virtual address."""

    def __init__(self, path: Path):
        self.data = path.read_bytes()
        header = struct.unpack_from("<I", self.data, 0x3C)[0]
        sections = struct.unpack_from("<H", self.data, header + 6)[0]
        optional = struct.unpack_from("<H", self.data, header + 20)[0]
        self.base = struct.unpack_from("<I", self.data, header + 24 + 28)[0]
        self.sections = []
        for index in range(sections):
            offset = header + 24 + optional + index * 40
            virtual, vsize = struct.unpack_from("<II", self.data, offset + 12)
            raw, praw = struct.unpack_from("<II", self.data, offset + 16)
            self.sections.append((self.base + virtual, vsize, praw, raw))

    def offset(self, va: int):
        for start, vsize, praw, raw in self.sections:
            if start <= va < start + max(vsize, raw):
                return praw + (va - start)
        return None

    def code(self, va: int, length: int) -> bytes:
        start = self.offset(va)
        return b"" if start is None else self.data[start:start + length]


def calls_from(image: Image, symbols: dict, handler: int, limit: int = 220) -> list:
    """Engine functions a handler reaches, in order, to the first return.

    Follows the fall-through only. A handler that ends in a tail jump into
    shared code is recorded as such rather than followed, because following it
    blindly is how a shared epilogue gets attributed to every caller.
    """
    try:
        import capstone
    except ImportError:
        return ["<capstone not installed>"]
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    found = []
    for instruction in md.disasm(image.code(handler, limit * 8), handler):
        if instruction.mnemonic == "call":
            operand = instruction.op_str
            if operand.startswith("0x"):
                target = int(operand, 16)
                name = symbols.get(target)
                if name and name not in NOISE and name not in found:
                    found.append(name)
            elif "[" in operand and "+" in operand:
                virtual = f"<virtual {operand}>"
                if virtual not in found:
                    found.append(virtual)
        elif instruction.mnemonic in ("ret", "retn"):
            break
        elif instruction.mnemonic == "jmp" and instruction.op_str.startswith("0x"):
            target = int(instruction.op_str, 16)
            name = symbols.get(target)
            if name and name not in NOISE:
                found.append(f"tail-call {name}")
            break
        if len(found) >= 12:
            break
    return found


def read_inventory(path: Path) -> dict:
    panels = {}
    current = None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        header = re.match(r"^(\S+)\s+dispatcher (0x[0-9A-Fa-f]+)", line)
        if header:
            current = header.group(1)
            panels[current] = {"dispatcher": int(header.group(2), 16), "events": {}}
            continue
        body = re.match(r"^\s+(0x[0-9A-Fa-f]+)\s+<- (.+)$", line)
        if body and current:
            handler = int(body.group(1), 16)
            for token in body.group(2).split(","):
                token = token.strip()
                if token.startswith("0x"):
                    panels[current]["events"][int(token, 16)] = handler
    return panels


def resolve(panel: dict, event: int):
    """The handler for exactly this event id. No alias substitution -- see above."""
    if event in panel["events"]:
        return event, panel["events"][event]
    return None, None


def alias_note(panel: dict, event: int) -> str:
    present = [a for a in EVENT_ALIASES.get(event, []) if a in panel["events"]]
    if not present:
        return ""
    return (" | panel implements the alias "
            + ", ".join(hex(a) for a in present)
            + " but not this code, so the button does not reach that handler")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--json", type=Path, help="write the raw matrix here")
    parser.add_argument("--panel", help="only this panel")
    arguments = parser.parse_args()

    if not INVENTORY.exists():
        print(f"missing {INVENTORY}; run tools/map_retained_gui_events.py --full")
        return 1
    exe = next((p for p in EXE_CANDIDATES if p.exists()), None)
    if exe is None:
        print("could not find swkotor.exe")
        return 1

    symbols = load_symbols()
    image = Image(exe)
    panels = read_inventory(INVENTORY)

    native_direction_panels = {
        name for name, info in panels.items()
        if info["events"].keys() & DIRECTION_EVENTS
    }

    matrix = {}
    for name in sorted(panels):
        if arguments.panel and arguments.panel.upper() not in name:
            continue
        info = panels[name]
        rows = []
        for button, (event, slot, code, kind) in BUTTON_EVENTS.items():
            if button in ROUTER_BUTTONS:
                action, source = ROUTER_BUTTONS[button]
                rows.append({
                    "button": button, "event": event, "slot": slot, "code": code,
                    "handler": None, "via_alias": None, "calls": [],
                    "action": action, "source": source,
                })
                continue
            used, handler = resolve(info, event)
            if handler is None:
                if button in ("Up", "Down", "Left", "Right"):
                    action = ("KMRP spatial navigation moves focus; the native "
                              "code is suppressed on this screen")
                    source = "KMRP spatial navigation"
                else:
                    action = ("panel does not implement it; CSWGuiPanel::"
                              "HandleInputEvent forwards it to the focused control"
                              + alias_note(info, event))
                    source = "Context-dependent (focused control decides)"
                rows.append({
                    "button": button, "event": event, "slot": slot, "code": code,
                    "handler": None, "via_alias": None, "calls": [],
                    "action": action, "source": source,
                })
                continue
            calls = calls_from(image, symbols, handler)
            note = ""
            source = kind
            if button in ("Up", "Down", "Left", "Right"):
                source = "Native KOTOR retained event"
            rows.append({
                "button": button, "event": event, "slot": slot, "code": code,
                "handler": handler,
                "via_alias": used if used != event else None,
                "calls": calls,
                "action": ("; ".join(calls) if calls else "handled, no named calls"),
                "source": source,
            })
        matrix[name] = {
            "dispatcher": info["dispatcher"],
            "navigates_itself": name in native_direction_panels,
            "implements": sorted(info["events"]),
            "rows": rows,
        }

    for name, entry in matrix.items():
        flag = "NATIVE-DIRECTIONS" if entry["navigates_itself"] else "KMRP-DIRECTIONS"
        print(f"\n=== {name}   dispatcher {entry['dispatcher']:#010x}   {flag}")
        for row in entry["rows"]:
            alias = ""
            handler = f"{row['handler']:#010x}" if row["handler"] else "-"
            print(f"  {row['button']:<6} ev {row['event']:#04x}{alias:<12} "
                  f"{handler:<12} {row['action'][:96]}")

    if arguments.json:
        arguments.json.write_text(json.dumps(matrix, indent=2), encoding="utf-8")
        print(f"\nwrote {arguments.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
